---
:resource: http://localhost:3000/
:minutes:
  - 3
  - 10
  - 50
  - 100
  - 500
:extra_messages:
  14: Extra message test!
:pause: 1
:email: jentcowork@gmail.com
:email2sms_email: itsjusttestforartec@sms.ru